import { Task } from '../types/task';

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Design system refinement',
    description: 'Update color palette and typography guidelines',
    status: 'done',
    priority: 'high',
    assignee: 'Sarah Chen',
    dueDate: '2026-05-01',
    createdAt: '2026-04-15',
    tags: ['design', 'documentation'],
  },
  {
    id: '2',
    title: 'API authentication middleware',
    description: 'Implement JWT token validation and refresh logic',
    status: 'in_progress',
    priority: 'high',
    assignee: 'Alex Johnson',
    dueDate: '2026-05-12',
    createdAt: '2026-04-20',
    tags: ['backend', 'security'],
  },
  {
    id: '3',
    title: 'Dashboard analytics module',
    description: 'Create interactive charts for task statistics',
    status: 'in_progress',
    priority: 'medium',
    assignee: 'Jordan Lee',
    dueDate: '2026-05-18',
    createdAt: '2026-04-25',
    tags: ['frontend', 'analytics'],
  },
  {
    id: '4',
    title: 'User profile page enhancement',
    description: 'Add avatar upload and profile customization',
    status: 'todo',
    priority: 'medium',
    assignee: 'Sam Rodriguez',
    dueDate: '2026-05-20',
    createdAt: '2026-05-02',
    tags: ['frontend', 'ui'],
  },
  {
    id: '5',
    title: 'Database migration script',
    description: 'Migrate from SQLite to PostgreSQL',
    status: 'todo',
    priority: 'high',
    assignee: 'Emma Taylor',
    dueDate: '2026-05-15',
    createdAt: '2026-05-05',
    tags: ['database', 'devops'],
  },
  {
    id: '6',
    title: 'Mobile responsive fixes',
    description: 'Fix layout issues on mobile devices',
    status: 'in_progress',
    priority: 'medium',
    assignee: 'Chris Park',
    dueDate: '2026-05-10',
    createdAt: '2026-04-30',
    tags: ['frontend', 'mobile'],
  },
  {
    id: '7',
    title: 'Unit tests for utilities',
    description: 'Add comprehensive test coverage for utils',
    status: 'done',
    priority: 'low',
    assignee: 'Morgan Liu',
    dueDate: '2026-04-28',
    createdAt: '2026-04-10',
    tags: ['testing', 'backend'],
  },
  {
    id: '8',
    title: 'Performance optimization',
    description: 'Reduce bundle size and improve load time',
    status: 'todo',
    priority: 'medium',
    assignee: 'Blake Wilson',
    dueDate: '2026-05-22',
    createdAt: '2026-05-08',
    tags: ['performance', 'frontend'],
  },
  {
    id: '9',
    title: 'Email notification system',
    description: 'Set up transactional emails for user actions',
    status: 'in_progress',
    priority: 'high',
    assignee: 'Diana Prince',
    dueDate: '2026-05-14',
    createdAt: '2026-04-28',
    tags: ['backend', 'notifications'],
  },
  {
    id: '10',
    title: 'Search functionality implementation',
    description: 'Add full-text search capability to tasks',
    status: 'in_progress',
    priority: 'medium',
    assignee: 'Frank Miller',
    dueDate: '2026-05-25',
    createdAt: '2026-05-03',
    tags: ['backend', 'search', 'database'],
  },
  {
    id: '11',
    title: 'API documentation',
    description: 'Create comprehensive API documentation with examples',
    status: 'done',
    priority: 'medium',
    assignee: 'Grace Wong',
    dueDate: '2026-05-05',
    createdAt: '2026-04-18',
    tags: ['documentation', 'backend'],
  },
  {
    id: '12',
    title: 'Dark mode implementation',
    description: 'Add dark mode toggle and persistence',
    status: 'todo',
    priority: 'low',
    assignee: 'Henry Clark',
    dueDate: '2026-05-28',
    createdAt: '2026-05-06',
    tags: ['frontend', 'ui', 'theme'],
  },
  {
    id: '13',
    title: 'User activity logging',
    description: 'Track and log user interactions for analytics',
    status: 'done',
    priority: 'high',
    assignee: 'Iris King',
    dueDate: '2026-05-02',
    createdAt: '2026-04-22',
    tags: ['backend', 'analytics', 'logging'],
  },
  {
    id: '14',
    title: 'Import/Export functionality',
    description: 'Allow users to import and export tasks as CSV',
    status: 'todo',
    priority: 'medium',
    assignee: 'Jack Davis',
    dueDate: '2026-05-30',
    createdAt: '2026-05-07',
    tags: ['frontend', 'backend', 'data'],
  },
  {
    id: '15',
    title: 'Real-time collaboration feature',
    description: 'Implement WebSocket for real-time updates',
    status: 'in_progress',
    priority: 'high',
    assignee: 'Kate Martin',
    dueDate: '2026-05-20',
    createdAt: '2026-05-01',
    tags: ['backend', 'websocket', 'realtime'],
  },
  {
    id: '16',
    title: 'Comments system on tasks',
    description: 'Add ability to comment and discuss tasks',
    status: 'in_progress',
    priority: 'medium',
    assignee: 'Leo Anderson',
    dueDate: '2026-05-19',
    createdAt: '2026-04-29',
    tags: ['frontend', 'backend', 'comments'],
  },
  {
    id: '17',
    title: 'Rate limiting implementation',
    description: 'Add API rate limiting for security',
    status: 'done',
    priority: 'high',
    assignee: 'Maria Garcia',
    dueDate: '2026-05-08',
    createdAt: '2026-04-24',
    tags: ['backend', 'security'],
  },
  {
    id: '18',
    title: 'Mobile app notifications',
    description: 'Push notifications for mobile clients',
    status: 'todo',
    priority: 'medium',
    assignee: 'Noah Jackson',
    dueDate: '2026-05-26',
    createdAt: '2026-05-04',
    tags: ['mobile', 'notifications'],
  },
  {
    id: '19',
    title: 'Advanced filtering options',
    description: 'Add complex filtering and saved filters',
    status: 'in_progress',
    priority: 'low',
    assignee: 'Olivia White',
    dueDate: '2026-05-27',
    createdAt: '2026-04-27',
    tags: ['frontend', 'ui', 'filters'],
  },
  {
    id: '20',
    title: 'Automated backup system',
    description: 'Daily automated backups to cloud storage',
    status: 'done',
    priority: 'high',
    assignee: 'Peter Brown',
    dueDate: '2026-05-03',
    createdAt: '2026-04-19',
    tags: ['devops', 'backup', 'database'],
  },
];
